### ISSUE TITLE
Add support for wait operation

### ISSUE THREAD

**Issue by Vacxe** [KakaoCup/Compose#31]
`ComposeTestRule` can provide functionality for awaiting views what can be useful for many test cases. However code below don't looks great to me.

```
fun BaseNode<*>.waitFor(composeTestRule: ComposeTestRule, timeoutMillis: Long = 1_000) {
    composeTestRule.waitUntil(timeoutMillis) {
        try {
            this.delegate.interaction.semanticsNodeInteraction.assertExists()
            true
        } catch (e: AssertionError) {
            false
        }
    }
}
```

Want to find a way how to do the same way but without composeTestRule reinjection to the function

At the end wanna have something like 

```
ComposeScreen.onComposeScreen<MyScreen>(composeTestRule) {
  waitFor()
      heading {
        waitFor()
        hasText(it)
      }
}
```

**Comment by matzuk** [comment]
As we have discussed earlier, there is the same functionality in Kaspresso. Do we need to duplicate it here?
