### ISSUE TITLE
Source code is not available directly from projects

### ISSUE THREAD

**Issue by Abhimanyu14** [KakaoCup/Compose#53]
Unable to view the source code from projects directly.

![image](https://github.com/KakaoCup/Compose/assets/29737108/d847d522-2e0f-492c-8f40-0b4a7ff52f22)

**Comment by Vacxe** [comment]
@Abhimanyu14 does it affecting any performance? Library is OSS and you always can look in source code in this repo.

**Comment by Abhimanyu14** [comment]
Thanks for responding. 
There are no performance issues. 

Some libraries like Jetpack Compose have source code available in the IDE itself. 
This makes the library source code navigation easier. 

Any particular reason for this lib to not have that? 
If not, is it possible to do so? 

Thanks.
