### ISSUE TITLE
0.3 version requeries java 17

### ISSUE THREAD

**Issue by kozaxinan** [KakaoCup/Compose#66]
https://github.com/KakaoCup/Compose/pull/54 
this change introduced java 17 as build jdk. but there is no need to update source and binary compability to java 17 at the moment. this will force users to match java target.

addind java and kotlin targets for java 8 or 11 could be enough.

**Comment by Vacxe** [comment]
https://developer.android.com/build/releases/gradle-plugin

<img width="889" alt="Screenshot 2024-03-05 at 9 40 14 am" src="https://github.com/KakaoCup/Compose/assets/2812510/c2c41e04-fadf-4f24-b97b-96f0570a2fb7">

Please take a look for Gradle-AGP-Java compatibility

**Comment by kozaxinan** [comment]
Isn't that requirement just for JDK? Source code compatibility and which JDK is being used to compile should be different topics, right? Original change could just update the jdk.

We use new agp with java 11 compatibility and jdk 17 for a while. We updated our source compatibility to 17 recently. 

This issue is not a blocker for us any more.

Feel free to close.
