### ISSUE TITLE
Problem with LazyColumn and clickable modifier

### ISSUE THREAD

**Issue by Majostik** [KakaoCup/Compose#79]
Hi
There is a problem with `LazyColumn `and `clickable `modifier, if I add `clickable` to item of `LazyColumn` then `KLazyListItemNode` can't find child. 
For example I modified your sample and tried to run

```
@Composable
private fun ListItemHeader(item: LazyListItem.Header, modifier: Modifier = Modifier) {
    Box(
        modifier = Modifier
            .padding(horizontal = 16.dp, vertical = 8.dp)
            .clickable {  }
            .clip(RoundedCornerShape(8.dp))
            .background(Color.Green)
            .then(modifier)
    ) {
        Text(
            item.title,
            Modifier
                .padding(8.dp)
                .testTag("LazyListHeaderTitle")
        )
    }
}
```

I got error 

```
java.lang.AssertionError: Failed to assert the following: (Text + EditableText = [Items from 1 to 10])
Can't retrieve node at index '0' of '(hasAnyAncestorThat(Semantics node id = 18)) && (TestTag = 'LazyListHeaderTitle')'
There are no existing nodes for that selector.
```

**Comment by EvgenyMeltsaykin** [comment]
Hi!  Check that your nodes use the flag useUnmergedTree = true

This [issue](https://github.com/KakaoCup/Compose/issues/43) contains examples of how it can be configured

**Comment by Majostik** [comment]
Yeah, it's working. Can you please explain why it's now working without this flag?

**Comment by EvgenyMeltsaykin** [comment]
You can read more about it [here](https://developer.android.com/jetpack/compose/semantics#merged-vs-unmerged)
